# Generated by Django 5.2.8 on 2025-12-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
