# Generated by Django 5.2.7 on 2025-10-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0002_alter_payment_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
