# Generated by Django 5.2.7 on 2025-10-24 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('fundraisers', '0003_alter_payment_stripe_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.story'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fundraiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fundraisers.fundraiser'),
        ),
    ]
