# Generated by Django 5.2.7 on 2025-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundraisers', '0004_payment_story_alter_payment_fundraiser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='succeeded',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
