# Generated by Django 5.2.7 on 2025-10-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_groupchatroom_remove_messageetogroup_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
