# Generated by Django 5.2.7 on 2025-12-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_groupmessage_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='color',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
