# Generated by Django 5.2.7 on 2025-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='story',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
