# Generated by Django 5.2.7 on 2025-12-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_story_pdf_file_story_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_magazine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='story_thumbnails/'),
        ),
    ]
