# Generated by Django 5.2.8 on 2025-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_while_at_school',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
