# Generated by Django 5.2.8 on 2025-12-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_name_while_at_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser_account',
        ),
    ]
