# Generated by Django 5.2.8 on 2025-12-13 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_user_is_superuser_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student_account',
            new_name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff_account',
        ),
    ]
